### ISSUE TITLE
I seem to have large caps in report.html

### ISSUE THREAD

**Issue by n0brainer** [tmhoule/JSSReport#4]
I have been using your report generator for a while and love it.  however, this recent version (Aug 21st(?)) seems to leave large gaps in the report.html. 

I get the Major OS X Versions graph, the General Mac Model types chart, and then a large blank area, then the file vault compliance, processor, and memory charts, then another blank section, and finally the total computers and report generation date/time.

OSX 10.10.5, Server 5.0.15

**Comment by tmhoule** [comment]
Those blank areas are 'missing' reports.  They may not be applicable in your environment.  The reports that should show are:

```
<div id=\"chart_divOsv\" style=\"width: 900px; height: 500px;\"></div>
<div id=\"chart_divMod\" style=\"width: 950px; height: 600px;\"></div>
<div id=\"chart_divMod2\" style=\"width: 1100px; height: 1100px;\"></div>
<div id=\"chart_divFV2\" style=\"width: 1100px; height: 600px;\"></div>
<div id=\"chart_divProc\" style=\"width: 950px; height: 600px;\"></div>
<div id=\"chart_divRam\" style=\"width: 950px; height: 600px;\"></div>
<div id=\"chart_divPO\" style=\"width: 950px; height: 1200px;\"></div>
<div id=\"chart_divEnroll\" style=\"width: 950px; height: 1200px;\"></div>
```

So you are missing Mod2 which is the detailed Mac Model chart.  You are also missing Purchase Order and Enrollment charts.  Perhaps your saved report does not contain the data needed to make the graphs?
