### ISSUE TITLE
Unable to get graph of model names

### ISSUE THREAD

**Issue by IMGreenTea** [tmhoule/JSSReport#5]
Hi, I have all the code running and everything is running smoothly but I am unable to get the model graph to appear on my report.html. I was just wondering if it had to do with the way I named my models for the computers (i.e. 13-inch MacBook Pro (2011) [Model] MacBookPro8,1 [Model Identifier]). Thank you for your time.

**Comment by tmhoule** [comment]
Looks like Google changed the chart calls - I could only have one bar graph chart.  Should be working now.
